---
document:
  -
    EOL: cr+lf
    codepage: 8bit
    config_file: ~
    cursor_pos: 0
    edit_pos: 1402
    file_path: '/home/lichtkind/code/perl/test/friendly/sniffer.pl'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: lf
    codepage: utf8
    config_file: ~
    cursor_pos: 775
    edit_pos: 0
    file_path: '/home/lichtkind/code/perl/test/friendly/snifferb.pl'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: 8bit
    config_file: ~
    cursor_pos: 0
    edit_pos: '-1'
    file_path: '/home/lichtkind/code/perl/test/friendly/sniffera.pl'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: 8bit
    config_file: ~
    cursor_pos: 0
    edit_pos: '-1'
    file_path: '/home/lichtkind/code/perl/test/friendly/snifferraw.pl'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 0
  -
    EOL: lf
    codepage: utf8
    config_file: ~
    cursor_pos: 2176
    edit_pos: 0
    file_path: '/home/lichtkind/txt/artikel/mystikum/meru.txt'
    folded_lines: []
    marked_lines: []
    readonly: 'off'
    syntaxmode: none
    tab_size: 4
    tab_use: 1
  -
    EOL: lf
    codepage: utf8
    config_file: ~
    cursor_pos: 284
    edit_pos: 283
    file_path: '/home/lichtkind/txt/arbeit/gw.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 1028
    edit_pos: 6402
    file_path: '/home/lichtkind/txt/artikel/$foo/rezension-sprachen.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: auto
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 1489
    edit_pos: '-1'
    file_path: '/home/lichtkind/txt/artikel/$foo/wxperl-tut_4.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: 0
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 1619
    edit_pos: '-1'
    file_path: '/home/lichtkind/txt/artikel/$foo/wxperl-tut_2.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 0
    edit_pos: '-1'
    file_path: '/home/lichtkind/txt/artikel/$foo/wxperl-tut_3.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 0
    edit_pos: '-1'
    file_path: '/home/lichtkind/txt/artikel/$foo/perl6-tut_2.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: 8bit
    config_file: ~
    cursor_pos: 0
    edit_pos: 1015
    file_path: '/home/lichtkind/code/perl/project/editor/dev/base/lib/Kephra/Dialog/Info.pm'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: perl
    tab_size: 4
    tab_use: 1
  -
    EOL: auto
    codepage: utf8
    config_file: ~
    cursor_pos: 4
    edit_pos: '-1'
    file_path: '/home/lichtkind/txt/artikel/$foo/wxperl-tut_7.txt'
    folded_lines: []
    marked_lines: []
    readonly: protect
    syntaxmode: none
    tab_size: 4
    tab_use: 0
